// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.MySQL")>]
[<assembly: AssemblyProductAttribute("SQLProvider.MySQL")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to MySQL.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.MySQL"
    let [<Literal>] AssemblyProduct = "SQLProvider.MySQL"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to MySQL."


