// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Firebird")>]
[<assembly: AssemblyProductAttribute("SQLProvider.Firebird")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to Firebird.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Firebird"
    let [<Literal>] AssemblyProduct = "SQLProvider.Firebird"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to Firebird."


