language: csharp
dist: trusty

sudo: false  # use the new container-based Travis infrastructure

services:
  - postgres

mono:
  - 5.0.1

os:
  - linux
  - osx

script:
  - ./build.sh All

branches:
  except:
  - gh-pages