init:
  - git config --global core.autocrlf input  
os: Windows Server 2012
services:
  - postgres95
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
