// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.MsSqlServer")>]
[<assembly: AssemblyProductAttribute("SQLProvider.MsSqlServer")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to MsSqlServer.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.MsSqlServer"
    let [<Literal>] AssemblyProduct = "SQLProvider.MsSqlServer"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to MsSqlServer."


