// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.SQLite")>]
[<assembly: AssemblyProductAttribute("SQLProvider.SQLite")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to SQLite.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.SQLite"
    let [<Literal>] AssemblyProduct = "SQLProvider.SQLite"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to SQLite."


