// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Oracle")>]
[<assembly: AssemblyProductAttribute("SQLProvider.Oracle")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to Oracle.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Oracle"
    let [<Literal>] AssemblyProduct = "SQLProvider.Oracle"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to Oracle."


