// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.ODBC")>]
[<assembly: AssemblyProductAttribute("SQLProvider.ODBC")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to ODBC.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.ODBC"
    let [<Literal>] AssemblyProduct = "SQLProvider.ODBC"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to ODBC."


