// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.Common")>]
[<assembly: AssemblyProductAttribute("SQLProvider.Common")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.Common"
    let [<Literal>] AssemblyProduct = "SQLProvider.Common"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access."


