// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.MSAccess")>]
[<assembly: AssemblyProductAttribute("SQLProvider.MSAccess")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to MSAccess.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.MSAccess"
    let [<Literal>] AssemblyProduct = "SQLProvider.MSAccess"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to MSAccess."


