// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SQLProvider.SQLServer")>]
[<assembly: AssemblyProductAttribute("SQLProvider.SQLServer")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access to SQLServer.")>]



do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SQLProvider.SQLServer"
    let [<Literal>] AssemblyProduct = "SQLProvider.SQLServer"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access to SQLServer."


